### ISSUE TITLE
Ruby-binding compilation error in OSX (Mavericks)

### ISSUE THREAD

**Issue by priancho** [chokkan/simstring#15]
I hope that this helps osx users who encountered the same problem.

After I upgraded to Mavericks, I couldn't make the ruby-binding of simstring since running make gave countless error messages such as "undefined templates" and "no matching function."

The problem was the gcc/g++ compilers in Makefile (in my case, it was "CC=clang" and "CXX=clang++").
I installed gcc/g++ through macports and replaced those lines with "CC=gcc" and "CXX=g++"

In addition, compiler makes an error that can't find simstring.h (I am not sure why it can't find it even though extconf.rb has CFLAGS="../../include").
After the include line is fixed (#include <simstring/simstring.h> --> #include <../../include/simstring/simstring.h>), make runs without any problem! :-)

**Comment by dav009** [comment]
probably stuck in the same problem.

I don't understand your instructions though
