### ISSUE TITLE
simstring python bindings will not build with libc++

### ISSUE THREAD

**Issue by soumith** [chokkan/simstring#16]
Clang on OSX defaults to libc++
The python provided by default in OSX is also linked against libc++, so, adding CPPFLAGS="-stdlib=libstdc++" is not an option.

The problem occurs in ngram.h:99
ngram.h line 99 fails largely because 
std::basic_stringstream<T> is only defined for T=char and T=wchar_t in libc++ while simstring tries to initialize it with a bunch of other types.

Is there any way to rewrite this?

**Comment by p-vital** [comment]
A somewhat less radical fix: https://github.com/vitalco/simstring-python-package/pull/1

While this builds a package on macs, running the unicode sample produces blank output.

**Comment by wollmers** [comment]
The only sane way would be: port to UTF-8. UTF-16/32 is a PITA.
