### ISSUE TITLE
Compilation error on LinuxUbuntu 

### ISSUE THREAD

**Issue by dimaxweb** [chokkan/simstring#9]
Hi ,
I follow instructions and running ./configure and then make  - which fails with following error:
Any chance you can help to figure out this quickly ?

make[2]: Entering directory `/home/tserver/Public/brat-v1.3_Crunchy_Frog/simstring-1.0/include'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/home/tserver/Public/brat-v1.3_Crunchy_Frog/simstring-1.0/include'
Making all in frontend
make[2]: Entering directory`/home/tserver/Public/brat-v1.3_Crunchy_Frog/simstring-1.0/frontend'
g++ -DHAVE_CONFIG_H -I. -I.. -I.. -I../include   -O3 -ffast-math  -O3 -ffast-math  -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
In file included from ../include/simstring/memory_mapped_file.h:62:0,
                 from ../include/simstring/simstring.h:52,
                 from main.cpp:43:
../include/simstring/memory_mapped_file_posix.h: In member function âvoid memory_mapped_file_posix::open(const string&, std::ios_base::openmode)â:
../include/simstring/memory_mapped_file_posix.h:91:17: error: â::closeâ has not been declared
../include/simstring/memory_mapped_file_posix.h: In member function âvoid memory_mapped_file_posix::close()â:
../include/simstring/memory_mapped_file_posix.h:106:13: error: â::closeâ has not been declared
../include/simstring/memory_mapped_file_posix.h: In member function âbool memory_mapped_file_posix::resize(memory_mapped_file_posix::size_type)â:
../include/simstring/memory_mapped_file_posix.h:126:17: error: â::lseekâ has not been declared
../include/simstring/memory_mapped_file_posix.h:128:48: error: âreadâ was not declared in this scope
../include/simstring/memory_mapped_file_posix.h:131:49: error: âwriteâ was not declared in this scope
make[2]: **\* [main.o] Error 1
make[2]: Leaving directory `/home/tserver/Public/brat-v1.3_Crunchy_Frog/simstring-1.0/frontend'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/tserver/Public/brat-v1.3_Crunchy_Frog/simstring-1.0'
make: **\* [all] Error 2

**Comment by p-vital** [comment]
unistd fix is in master, the remaining issue has to do with clang and has partial fixes in #16.

**Comment by danaludwig** [comment]
For the second problem: python setup.py build_ext

the fix "#include <stddef.h>" didn't work for me, but I googled the error, and it turns out that Python 3 dropped all those functions.  So if you want to build with python2, and you have it installed, but "python" maps to "python3", then you can explicitly call python2, that is:

python2 setup.py build_ext

And for me, that made the errors go away

**Comment by cynthia** [comment]
A fix for the original issue has landed on master - I think if the Python issue is still a problem (I'm still going through the backlog) that probably should be discussed in #16.
